name: calendario_ore
description: Un'app Flutter con calendario elegante e gestione numeri giornalieri.


version: 1.0.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  # Pacchetti principali aggiornati
  table_calendar: ^3.2.0
  shared_preferences: ^2.5.3

  pdf: ^3.10.7
  printing: ^5.12.0

  flutter_localizations:
    sdk: flutter
  rename: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
